title: huigu.com
description: "BLCM`s personal webview"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: b886866b@163.com
github_username: github
twitter_username: twitter
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo: blcm996/blcm996.github.io
giscus_repoId: R_kgDOLt8gsg
giscus_category: Announcements
giscus_categoryId: DIC_kwDOLt8gss4Ce5jw
goatcounter_code: blcm
google_analytics:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "2024-04-14"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true

#<script src="https://giscus.app/client.js"
#data-repo="blcm996/blcm996.github.io"
#data-repo-id="R_kgDOLt8gsg"
#data-category="Announcements"
#data-category-id="DIC_kwDOLt8gss4Ce5jw"
#data-mapping="pathname"
#data-strict="0"
#data-reactions-enabled="1"
#data-emit-metadata="0"
#data-input-position="bottom"
#data-theme="dark_dimmed"
#data-lang="zh-CN"
#crossorigin="anonymous"
#async>
#</script>
